### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by PLP-Consulting** [standardebooks/mark-twain_personal-recollections-of-joan-of-arc#2]
https://github.com/standardebooks/mark-twain_personal-recollections-of-joan-of-arc/blob/11a407d37f5e7061c38cdd8b85b43f8e904c03e1/src/epub/text/chapter-2-16.xhtml#L88

"...the garrisons on the other wide..." (should be "other side")

https://archive.org/details/personalrecollec00clem/page/259/mode/1up

-----

https://github.com/standardebooks/mark-twain_personal-recollections-of-joan-of-arc/blob/11a407d37f5e7061c38cdd8b85b43f8e904c03e1/src/epub/text/chapter-2-19.xhtml#L16

"...the chair were..." (should be "chairs")

https://archive.org/details/personalrecollec00clem/page/274/mode/1up

-----

https://github.com/standardebooks/mark-twain_personal-recollections-of-joan-of-arc/blob/master/src/epub/text/chapter-2-19.xhtml#L21

"...full of compassion and sorry and despair!" (should be "sorrow")

https://archive.org/details/personalrecollec00clem/page/276/mode/1up

-----

https://github.com/standardebooks/mark-twain_personal-recollections-of-joan-of-arc/blob/11a407d37f5e7061c38cdd8b85b43f8e904c03e1/src/epub/text/chapter-2-20.xhtml#L42

"We crossed the five..." (should be "river")

https://archive.org/details/personalrecollec00clem/page/281/mode/1up

-----
https://github.com/standardebooks/mark-twain_personal-recollections-of-joan-of-arc/blob/11a407d37f5e7061c38cdd8b85b43f8e904c03e1/src/epub/text/chapter-2-32.xhtml#L16

"When we reached Orleans that tow was..." (should be "town")

https://archive.org/details/personalrecollec00v2gclem/page/33/mode/1up

-----

https://github.com/standardebooks/mark-twain_personal-recollections-of-joan-of-arc/blob/11a407d37f5e7061c38cdd8b85b43f8e904c03e1/src/epub/text/chapter-2-35.xhtml#L14

"It was here hat we saw..." (should be "that")

https://archive.org/details/personalrecollec00v2gclem/page/49/mode/1up

-----

https://github.com/standardebooks/mark-twain_personal-recollections-of-joan-of-arc/blob/11a407d37f5e7061c38cdd8b85b43f8e904c03e1/src/epub/text/chapter-2-39.xhtml#L16

"The Joan dismissed me..." (should be "Then")

https://archive.org/details/personalrecollec00v2gclem/page/94/mode/1up

**Comment by acabal** [comment]
Thanks!
